"""init

Revision ID: 9ef9f6d69f91
Revises: 
Create Date: 2026-06-26 13:50:40.548753
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef9f6d69f91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('subdominio', sa.String(length=63), nullable=False),
    sa.Column('email_admin', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('color_acento', sa.String(length=9), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'suspendido', name='estado_empresa'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_subdominio'), 'empresa', ['subdominio'], unique=True)
    op.create_table('perfil',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nombre', name='uq_perfil_tenant_nombre')
    )
    op.create_index(op.f('ix_perfil_tenant_id'), 'perfil', ['tenant_id'], unique=False)
    op.create_table('usuario',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.Enum('superadmin', 'admin_empresa', name='rol_usuario'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_tenant_id'), 'usuario', ['tenant_id'], unique=False)
    op.create_table('evaluado',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('perfil_id', sa.Uuid(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_evaluado_tenant_email')
    )
    op.create_index(op.f('ix_evaluado_tenant_id'), 'evaluado', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluado_tenant_id'), table_name='evaluado')
    op.drop_table('evaluado')
    op.drop_index(op.f('ix_usuario_tenant_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_perfil_tenant_id'), table_name='perfil')
    op.drop_table('perfil')
    op.drop_index(op.f('ix_empresa_subdominio'), table_name='empresa')
    op.drop_table('empresa')
    # ### end Alembic commands ###
